# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jacob hoover vigly
email: jacob.hoover@mail.mcgill.ca
description: > # this means to ignore newlines until "baseurl:"
  Scientific Program Coordinator at CHI FRO, LLC. Formerly Postdoc at MIT, Department of Brain and Cognitive Sciences. PhD in Linguistics from McGill University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jahoo.github.io" # the base hostname & protocol for your site
google_scholar_id: koLi2TwAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge

scholar:
  style: apa
  locale: en
  sort_by: [year, month, day]
  order: descending
  # group_by: year
  # group_order: descending
  bibtex_skip_fields: ["abstract", "code", "handout", "month_numeric", "myurl", "myurltitle", "openaccess", "pdf", "poster", "preprint", "slides"]
  # type_names: { article: Papers }
  # linebreaks: true # 
  source: /_bibliography
  bibliography: default.bib
  bibliography_template: bib # references file _layouts/bib.*

# USE THE FOLLOWING FOR MATH:
# $$\LaTeX code$$   (for display)
# \\[\LaTeX code\\] (also for display)
# \\(\LaTeX code\\) (for inline)
